package versions

object Versions {
    const val core = "1.9.0"
    const val appCompat = "1.6.1"
    const val materialUi = "1.6.1"
    const val constraintLayout = "2.1.4"
    const val navigation = "2.5.3"
    const val retrofit = "2.9.0"
    const val gsonConverter = "2.9.0"
    const val okhttp = "4.9.0"
    const val okhttpInterceptor = "5.0.0-alpha.3"
    const val chucker = "3.5.2"
    const val paging = "3.1.1"
    const val rxAndroid = "3.0.0"
    const val rxJava = "3.0.7"
    const val rxBinding = "3.0.0"
    const val glide = "4.12.0"
    const val shimmer = "0.5.0"
    const val prettyTime = "4.0.4.Final"
    const val dagger = "2.44"
    const val hilt = "1.0.0"
    const val testJunit = "4.13.2"
    const val androidJunit = "1.1.5"
    const val espresso = "3.4.0"
}